version: "3.8"

services:
  db:
    image: mysql:8.0.35
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootcsleepwd
      MYSQL_DATABASE: cslee
      MYSQL_USER: cslee
      MYSQL_PASSWORD: cslee_password
    ports:
      - "3305:3306"
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]


volumes:
  mysql_data:
